apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: nogadocker/dind-agent
      imagePullPolicy: Always
      securityContext:
        privileged: true
    - name: python
      image: python:3.9-slim
      command:
        - sleep
        - infinity
