# apiVersion: v1
# kind: Pod
# spec:
#   containers:
#   - name: dind
#     image: drpsychick/dind-buildx-helm
#     alwaysPull: true
#     securityContext:
#       privileged: true
#     volumeMounts:
#     - mountPath: /var/run
#       name: docker-sock
#   volumes:
#   - name: docker-sock
#   emptyDir: {}

apiVersion: v1
kind: Pod
spec:
  containers:
    - name: dind
      image: docker:24.0.5-dind # Docker image with docker-compose
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
    - name: helper
      image: docker/compose:1.29.2 # Standalone docker-compose
      command:
        - cat
  volumes:
    - name: docker-sock
      emptyDir: {}
