apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/noga-x-space/music-list-app
    targetRevision: HEAD
    path: ./spotify-db
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo-db
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
