apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.port }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-mongodb