apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ .Release.Name }}-web
  namespace: dev
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
        - name: web
          image: {{ .Values.web.image }}:{{ .Values.web.tag }}
          ports:
            - containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
            - name: MONGO_HOST
              value: {{ .Release.Name }}-db.mongo-db.svc.cluster.local
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_PORT
              value: "{{ .Values.mongodb.port }}"