# spotify-ish/values.yaml
web:
  image: nogadocker/spotify
  tag: latest
  port: 5000
  replicas: 1
  namespace: dev
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
  mongodb:
    host: spotify-db-mongodb.mongo-db.svc.cluster.local
    port: 27017
