# Main namespace for all components
namespace: spotify-app
# MongoDB configurations
mongodb:
  image: mongo
  tag: latest
  port: 27017
  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi
  service:
    type: ClusterIP
    port: 27017
# Web application configurations
web:
  image: nogadocker/spotify
  tag: "18"
  port: 5000
  replicas: 1
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
