mongodb:
  image: mongo:latest
  port: 27017
  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi

web:
  image: nogadocker/spotify
  tag: latest
  port: 5000
  replicas: 1
  service:
    type: NodePort
    port: 5000
    targetPort: 5000

secrets:
  mongoCredentials:
    username: "" # Set your MongoDB username
    password: "" # Set your MongoDB password

# secrets:
#   mongoCredentials:
#     username:
#       valueFrom:
#         secretKeyRef:
#           name: mongo-credentials
#           key: MONGO_INITDB_ROOT_USERNAME
#     password:
#       valueFrom:
#         secretKeyRef:
#           name: mongo-credentials
#           key: MONGO_INITDB_ROOT_PASSWORD
